language: scala
script:
  - sbt ++\$TRAVIS_SCALA_VERSION clean update compile test package
scala:
  - $scalaVersion$
jdk:
  - oraclejdk7
notifications:
  email:
    - olafurpg@gmail.com
branches:
  only:
    - master
